language: php
php:
  - 7.0
install:
  - composer install
script:
  - ./vendor/bin/phpcs -p --standard=PSR2 ./src ./tests
  - ./scripts/phpunit.sh
  - ./scripts/humbug.sh
  - ./scripts/build.sh
deploy:
  provider: script
  skip_cleanup: true
  script: ./scripts/deploy.sh
  on:
    tags: true
    php: 7.0