sudo: required
dist: trusty
language: php
php:
  - 7.0
before_install:
  - sudo rm -rf ~/.nvm - curl -sL "https://deb.nodesource.com/setup_7.x" | sudo -E bash -
  - sudo apt-get install -y nodejs
install:
  - composer install
  - npm install
script:
  - ./vendor/bin/phpcs -p --standard=PSR2 ./src ./tests
  - ./scripts/phpunit.sh
  - ./scripts/humbug.sh
  - ./scripts/build.sh
deploy:
  provider: script
  skip_cleanup: true
  script: ./scripts/deploy.sh
  on:
    tags: true
    php: 7.0